
[env]
TERM = "xterm-256color"


[scrolling]
history               = 65535

[cursor.style]
shape                 = "Beam"
blinking              = "Always"

[cursor.vi_mode_style]
shape                 = "Block"
blinking              = "Off"

[cursor]
blink_interval        = 500
blink_timeout         = 0
#unfocused_hollow      = true
#thickness             = 0.15

[terminal]
#osc52                 = "OnlyCopy"

[mouse]
hide_when_typing      = true
bindings = [
  { mouse = "Middle", action = "PasteSelection" },
]

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono NFM"
#family = "CaskaydiaCove Nerd Font"
style = "Bold"

[font.bold_italic]
#family = "CaskaydiaCove Nerd Font"
family = "JetBrainsMono NFM"
style = "Bold Italic"

[font.italic]
#family = "CaskaydiaCove Nerd Font"
family = "JetBrainsMono NFM"
style = "Italic"

[font.normal]
family = "JetBrainsMono NFM"
#family = "CaskaydiaCove Nerd Font"
style = "Regular"

[general]
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[selection]
#semantic_escape_chars = ",│‘|:"' ()[]{}<>t"
save_to_clipboard     = true
